import { VariantProps, cva } from "class-variance-authority";

export type BaseModalProps = VariantProps<typeof baseModal>;

export const baseModal = cva([''], {
  variants: {
    height: {
      auto: ['h-auto'],
      full: ['h-full'],
      screen: ['h-screen'],
      '0': ['h-0'],
      '1': ['h-1'],
      '2': ['h-2'],
      '3': ['h-3'],
      '4': ['h-4'],
      '5': ['h-5'],
      '6': ['h-6'],
      '8': ['h-8'],
      '10': ['h-10'],
      '12': ['h-12'],
    },
    width: {
      auto: ['w-auto'],
      full: ['w-full'],
      screen: ['w-screen'],
      '0': ['w-0'],
      '1': ['w-1'],
      '2': ['w-2'],
      '3': ['w-3'],
      '4': ['w-4'],
      '5': ['w-5'],
      '6': ['w-6'],
      '8': ['w-8'],
      '10': ['w-10'],
      '12': ['w-12'],
    },
    opacity: {
      0: ['opacity-0'],
      25: ['opacity-25'],
      50: ['opacity-50'],
      75: ['opacity-75'],
      100: ['opacity-100'],
    },
    overflow: {
      auto: ['overflow-auto'],
      hidden: ['overflow-hidden'],
      visible: ['overflow-visible'],
      scroll: ['overflow-scroll'],
    },
    color: {
      gray: ['bg-gray-500'],
      black: ['bg-black'],
      white: ['bg-white'],
    },
    padding: {
      none: ['p-0'],
      xs: ['p-1'],
      sm: ['p-2'],
      md: ['p-4'],
      lg: ['p-6'],
      xl: ['p-8'],
    },
    borderRadius: {
      none: ['rounded-none'],
      sm: ['rounded-sm'],
      md: ['rounded-md'],
      lg: ['rounded-lg'],
      xl: ['rounded-xl'],
      full: ['rounded-full'],
    },
    boxShadow: {
      xs: ['shadow-xs'],
      sm: ['shadow-sm'],
      md: ['shadow-md'],
      lg: ['shadow-lg'],
      xl: ['shadow-xl'],
      '2xl': ['shadow-2xl'],
      inner: ['shadow-inner'],
      outline: ['shadow-outline'],
      none: ['shadow-none'],
    },
  },
  defaultVariants: {
    height: 'auto',
    width: 'auto',
    opacity: 100,
    overflow: 'auto',
    color: 'white',
    padding: 'md',
    borderRadius: 'md',
    boxShadow: 'md',
  },
});
